#!/bin/bash

while true
do

	# Source for node configs
	# http://www.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/
	#nodejs --nouse-idle-notification --expose-gc --max-new-space-size=2048 --max-old-space-size=8192 dist/js/server.js
	node --nouse-idle-notification --expose-gc dist/js/server.js

	echo "Server Shutdown... restarting in 20 seconds"
	./emailcrash
	sleep 20
done
